import mongoose from 'mongoose';
import { Product } from '../models/product.model.js';
import { productRepository } from '../repositories/product.repository.js';
import { ProductBatch } from '../models/productBatch.model.js';
import { companyRepository } from '../../masters/repositories/company.repository.js';
import { categoryRepository } from '../../masters/repositories/category.repository.js';
import { unitRepository } from '../../masters/repositories/unit.repository.js';
import { baseMasterService } from '../../../common/baseMaster.service.js';
import { AppError } from '../../../utils/appError.js';
import { HTTP_STATUS } from '../../../common/httpStatuses.js';
import { logger } from '../../../config/logger.config.js';
import { PurchaseItem } from '../../purchases/models/purchaseItem.model.js';
import { SalesInvoice } from '../../sales/models/salesInvoice.model.js';
import { StockLedger } from '../../purchases/models/stockLedger.model.js';

export const productService = {
  // ONE-TIME CLEANUP: Permanently remove auto-generated batch numbers (BATCH-*, AUTO*) from database
  async cleanupAutoGeneratedBatches() {
    try {
      const result = await ProductBatch.deleteMany({
        $or: [
          { batchNumber: { $regex: '^BATCH-', $options: 'i' } },
          { batchNumber: { $regex: '^AUTO', $options: 'i' } },
        ],
      });
      if (result.deletedCount > 0) {
        logger.info(`🧹 ONE-TIME CLEANUP: Permanently deleted ${result.deletedCount} auto-generated batch records (BATCH-*, AUTO*).`);
      }
    } catch (err) {
      logger.error({ err }, 'Error executing auto-generated batch cleanup');
    }
  },

  async getTopSellingProducts(query = {}) {
    await this.cleanupAutoGeneratedBatches();

    // 1. Aggregate SalesInvoice items to calculate total quantity sold per product
    const salesAggregation = await SalesInvoice.aggregate([
      { $unwind: '$items' },
      {
        $group: {
          _id: '$items.productId',
          totalSoldQty: { $sum: { $toDouble: { $ifNull: ['$items.quantity', 0] } } },
        },
      },
      { $sort: { totalSoldQty: -1 } },
    ]);

    const salesMap = new Map();
    salesAggregation.forEach((item) => {
      if (item._id) salesMap.set(item._id.toString(), item.totalSoldQty);
    });

    // 2. Fetch active products (with optional search filter)
    const filter = { isActive: true };
    if (query.inStock === 'true' || query.inStockOnly === 'true') {
      filter.totalStock = { $gt: 0 };
    }

    if (query.search && query.search.trim()) {
      const searchRegex = new RegExp(query.search.trim(), 'i');
      filter.$or = [
        { name: searchRegex },
        { code: searchRegex },
        { barcode: searchRegex },
      ];
    }

    const productsDocs = await productRepository.findAllPopulated(filter, { sort: { name: 1 } });

    // Fetch associated product batches for bulk active FIFO batch attachment
    const productIds = productsDocs.map((p) => p._id);
    const allBatches = await ProductBatch.find({
      productId: { $in: productIds },
      isActive: true,
      batchNumber: { $not: /^BATCH-/i },
    }).lean().exec();

    const batchMap = {};
    allBatches.forEach((b) => {
      const pid = b.productId.toString();
      if (!batchMap[pid]) batchMap[pid] = [];
      batchMap[pid].push(b);
    });

    // Attach totalSoldQty, active batches, and effective FIFO selling price to each product
    const productsWithSales = productsDocs.map((pDoc) => {
      const pObj = pDoc.toObject ? pDoc.toObject() : { ...pDoc };
      const pIdStr = pObj._id.toString();
      const pBatches = (batchMap[pIdStr] || []).sort((a, b) => new Date(a.createdAt || 0) - new Date(b.createdAt || 0));
      const activeBatches = pBatches.filter((b) => (b.currentStock > 0 || b.quantityRemaining > 0) && b.isActive !== false);
      const oldestActiveBatch = activeBatches[0] || null;
      const upcomingBatch = activeBatches[1] || null;

      const effectiveSellingPrice = oldestActiveBatch?.sellingPrice > 0
        ? Number(oldestActiveBatch.sellingPrice)
        : Number(pObj.defaultSellingPrice || pObj.sellingPrice || 0);

      pObj.totalSoldQty = salesMap.get(pIdStr) || 0;
      pObj.batches = activeBatches.length > 0 ? activeBatches : pBatches;
      pObj.activeBatches = activeBatches;
      pObj.currentActiveBatch = oldestActiveBatch;
      pObj.upcomingBatch = upcomingBatch;
      pObj.currentSellingPrice = effectiveSellingPrice;
      pObj.sellingPrice = effectiveSellingPrice;
      pObj.defaultSellingPrice = effectiveSellingPrice;

      return pObj;
    });

    // Sort: Primary by totalSoldQty DESC, Secondary by totalStock DESC, Tertiary by name ASC
    productsWithSales.sort((a, b) => {
      if (b.totalSoldQty !== a.totalSoldQty) {
        return b.totalSoldQty - a.totalSoldQty;
      }
      if ((b.totalStock || 0) !== (a.totalStock || 0)) {
        return (b.totalStock || 0) - (a.totalStock || 0);
      }
      return (a.name || '').localeCompare(b.name || '');
    });

    return {
      products: productsWithSales,
      total: productsWithSales.length,
    };
  },

  async seedDefaultProducts() {
    return;
  },

  async getAllProducts(query = {}) {
    // Run batch cleanup before returning products list
    await this.cleanupAutoGeneratedBatches();

    const filter = {};
    if (query.search && query.search.trim()) {
      const searchRegex = new RegExp(query.search.trim(), 'i');

      // Lookup matching Brands / Companies
      const matchingBrands = await companyRepository.findAll({ name: searchRegex });
      const brandIds = matchingBrands.map((b) => b._id);

      // Lookup matching Categories
      const matchingCategories = await categoryRepository.findAll({ name: searchRegex });
      const categoryIds = matchingCategories.map((c) => c._id);

      // Lookup matching Batches
      const matchingBatches = await ProductBatch.find({ batchNumber: searchRegex, isActive: true }).lean().exec();
      const batchProductIds = matchingBatches.map((b) => b.productId);

      filter.$or = [
        { name: searchRegex },
        { code: searchRegex },
        { barcode: searchRegex },
      ];

      if (brandIds.length > 0) filter.$or.push({ brandId: { $in: brandIds } });
      if (categoryIds.length > 0) filter.$or.push({ categoryId: { $in: categoryIds } });
      if (batchProductIds.length > 0) filter.$or.push({ _id: { $in: batchProductIds } });
    }

    const brandId = query.brandId || query.companyId;
    if (brandId) filter.brandId = brandId;
    if (query.categoryId) filter.categoryId = query.categoryId;
    if (query.isActive !== undefined) {
      filter.isActive = query.isActive === 'true' || query.isActive === true;
    } else if (query.includeInactive !== 'true' && query.includeDeleted !== 'true') {
      filter.isActive = { $ne: false };
    }

    // Hide zero-stock products if inStock filter is passed
    if (query.inStock === 'true' || query.inStockOnly === 'true') {
      filter.totalStock = { $gt: 0 };
    }

    const sort = { name: 1 };
    const productsDocs = await productRepository.findAllPopulated(filter, { sort });
    const total = await productRepository.count(filter);

    // FETCH ASSOCIATED PRODUCT BATCHES FOR ALL PRODUCTS IN A SINGLE BULK QUERY (EXCLUDING AUTO-GENERATED BATCHES)
    const productIds = productsDocs.map((p) => p._id);
    const allBatches = await ProductBatch.find({
      productId: { $in: productIds },
      isActive: true,
      batchNumber: { $not: /^BATCH-/i },
    }).lean().exec();

    const batchMap = {};
    allBatches.forEach((b) => {
      const pid = b.productId.toString();
      if (!batchMap[pid]) batchMap[pid] = [];
      batchMap[pid].push(b);
    });

    // BULK AGGREGATIONS FOR INWARD (PURCHASES) & OUTWARD (SALES) METRICS
    const purchaseAgg = await PurchaseItem.aggregate([
      {
        $lookup: {
          from: 'purchases',
          localField: 'purchaseId',
          foreignField: '_id',
          as: 'purchaseDoc',
        },
      },
      {
        $unwind: { path: '$purchaseDoc', preserveNullAndEmptyArrays: true },
      },
      {
        $group: {
          _id: '$productId',
          totalPurchasedQty: { $sum: { $toDouble: { $ifNull: ['$quantity', 0] } } },
          lastPurchaseDate: { $max: { $ifNull: ['$purchaseDoc.purchaseDate', '$createdAt'] } },
        },
      },
    ]);

    const purchaseMap = new Map();
    purchaseAgg.forEach((item) => {
      if (item._id) {
        purchaseMap.set(item._id.toString(), {
          totalPurchasedQty: item.totalPurchasedQty || 0,
          lastPurchaseDate: item.lastPurchaseDate || null,
        });
      }
    });

    const salesAgg = await SalesInvoice.aggregate([
      { $unwind: '$items' },
      {
        $group: {
          _id: '$items.productId',
          totalSoldQty: { $sum: { $toDouble: { $ifNull: ['$items.quantity', 0] } } },
          lastSaleDate: { $max: { $ifNull: ['$date', '$createdAt'] } },
        },
      },
    ]);

    const salesMap = new Map();
    salesAgg.forEach((item) => {
      if (item._id) {
        salesMap.set(item._id.toString(), {
          totalSoldQty: item.totalSoldQty || 0,
          lastSaleDate: item.lastSaleDate || null,
        });
      }
    });

    // ATTACH BATCHES, INWARD/OUTWARD METRICS, EFFECTIVE SELLING PRICE, AND LAST DATES TO EACH PRODUCT DOCUMENT
    const products = productsDocs.map((pDoc) => {
      const pObj = pDoc.toObject ? pDoc.toObject() : { ...pDoc };
      const pIdStr = pObj._id.toString();
      const pBatches = (batchMap[pIdStr] || []).sort((a, b) => new Date(a.createdAt || 0) - new Date(b.createdAt || 0));

      const activeBatches = pBatches.filter((b) => (b.currentStock > 0 || b.quantityRemaining > 0) && b.isActive !== false);
      const oldestActiveBatch = activeBatches[0] || null;
      const effectiveSellingPrice = oldestActiveBatch?.sellingPrice > 0
        ? Number(oldestActiveBatch.sellingPrice)
        : Number(pObj.defaultSellingPrice || 0);

      const primaryBatchNumber = oldestActiveBatch?.batchNumber || pBatches[0]?.batchNumber || undefined;

      const purData = purchaseMap.get(pIdStr) || {};
      const saleData = salesMap.get(pIdStr) || {};

      // Compute accurate stock value from remaining batch layers
      let calculatedStockValue = 0;
      let unallocatedStock = Math.max(0, Number(pObj.totalStock || 0));

      if (pBatches.length > 0) {
        pBatches.forEach((b) => {
          const bStock = Math.max(0, Number(b.currentStock ?? b.quantityRemaining ?? 0));
          const bRate = Number(b.purchaseRate || 0);
          calculatedStockValue += bStock * bRate;
          unallocatedStock -= bStock;
        });
      }

      if (unallocatedStock > 0) {
        calculatedStockValue += unallocatedStock * Number(pObj.defaultPurchaseRate || 0);
      }

      return {
        ...pObj,
        defaultSellingPrice: effectiveSellingPrice,
        sellingPrice: effectiveSellingPrice,
        currentSellingPrice: effectiveSellingPrice,
        stockValue: calculatedStockValue,
        totalStockValue: calculatedStockValue,
        batches: pBatches,
        activeBatches,
        currentActiveBatch: oldestActiveBatch,
        upcomingBatch: activeBatches[1] || null,
        activeBatchCount: activeBatches.length,
        batchNumber: primaryBatchNumber,
        batchCode: primaryBatchNumber,
        totalPurchasedQty: purData.totalPurchasedQty || 0,
        lastPurchaseDate: purData.lastPurchaseDate || null,
        totalSoldQty: saleData.totalSoldQty || 0,
        lastSaleDate: saleData.lastSaleDate || null,
      };
    });

    return { products, total };
  },

  async getProductById(id) {
    if (!mongoose.Types.ObjectId.isValid(id)) {
      throw new AppError(`Invalid Product ID format: '${id}'`, HTTP_STATUS.BAD_REQUEST);
    }

    // Automatically reconcile product batch stock against purchases and sales
    await this.reconcileProductBatches(id);

    const productDoc = await productRepository.findByIdPopulated(id);
    if (!productDoc) {
      throw new AppError('Product not found', HTTP_STATUS.NOT_FOUND);
    }
    const rawBatches = await productRepository.findBatchesByProduct(id);
    const validBatches = rawBatches
      .filter((b) => b.batchNumber && !b.batchNumber.toUpperCase().startsWith('BATCH-'))
      .sort((a, b) => new Date(a.createdAt || 0) - new Date(b.createdAt || 0));

    const productObj = productDoc.toObject ? productDoc.toObject() : { ...productDoc };

    const activeBatches = validBatches.filter((b) => (b.currentStock > 0 || b.quantityRemaining > 0) && b.isActive !== false);
    const oldestActiveBatch = activeBatches[0] || null;
    const upcomingBatch = activeBatches[1] || null;
    const effectiveSellingPrice = oldestActiveBatch?.sellingPrice > 0
      ? Number(oldestActiveBatch.sellingPrice)
      : Number(productObj.defaultSellingPrice || 0);

    const annotatedBatches = validBatches.map((b) => {
      const bObj = b.toObject ? b.toObject() : { ...b };
      let status = 'DEPLETED';
      if ((bObj.currentStock > 0 || bObj.quantityRemaining > 0) && bObj.isActive !== false) {
        if (oldestActiveBatch && bObj._id.toString() === oldestActiveBatch._id.toString()) {
          status = 'ACTIVE';
        } else {
          status = 'UPCOMING';
        }
      }
      return {
        ...bObj,
        status,
        quantityPurchased: bObj.initialQuantity ?? bObj.quantityPurchased ?? 0,
        quantityRemaining: bObj.currentStock ?? bObj.quantityRemaining ?? 0,
      };
    });

    let calculatedStockValue = 0;
    let unallocatedStock = Math.max(0, Number(productObj.totalStock || 0));
    annotatedBatches.forEach((b) => {
      const bStock = Math.max(0, Number(b.currentStock ?? b.quantityRemaining ?? 0));
      const bRate = Number(b.purchaseRate || 0);
      calculatedStockValue += bStock * bRate;
      unallocatedStock -= bStock;
    });
    if (unallocatedStock > 0) {
      calculatedStockValue += unallocatedStock * Number(productObj.defaultPurchaseRate || 0);
    }

    const primaryBatchNumber = oldestActiveBatch?.batchNumber || annotatedBatches[0]?.batchNumber || undefined;

    return {
      product: {
        ...productObj,
        defaultSellingPrice: effectiveSellingPrice,
        sellingPrice: effectiveSellingPrice,
        currentSellingPrice: effectiveSellingPrice,
        currentActiveBatch: oldestActiveBatch,
        upcomingBatch: upcomingBatch,
        activeBatchCount: activeBatches.length,
        stockValue: calculatedStockValue,
        totalStockValue: calculatedStockValue,
        batches: annotatedBatches,
        batchNumber: primaryBatchNumber,
        batchCode: primaryBatchNumber,
      },
      batches: annotatedBatches,
    };
  },

  async reconcileProductBatches(productId) {
    if (!productId || !mongoose.Types.ObjectId.isValid(productId)) return null;

    const product = await productRepository.findById(productId);
    if (!product) return null;

    const batches = await ProductBatch.find({
      productId,
      batchNumber: { $not: /^BATCH-/i },
    }).sort({ createdAt: 1 }).exec();

    if (!batches || batches.length === 0) return null;

    const invoices = await SalesInvoice.find({ 'items.productId': productId })
      .sort({ date: 1, createdAt: 1 })
      .lean()
      .exec();

    let totalSoldQty = 0;
    invoices.forEach((inv) => {
      (inv.items || []).forEach((item) => {
        if (item.productId && item.productId.toString() === productId.toString()) {
          totalSoldQty += Number(item.quantity || 0);
        }
      });
    });

    let remainingSoldToAllocate = totalSoldQty;
    let totalStockAcc = 0;

    for (const batch of batches) {
      const initQty = Math.max(0, Number(batch.initialQuantity ?? batch.quantityPurchased ?? 0));
      const consumedQty = Math.min(initQty, remainingSoldToAllocate);
      const newStock = Math.max(0, initQty - consumedQty);

      batch.currentStock = newStock;
      batch.isActive = newStock > 0;
      await batch.save();

      totalStockAcc += newStock;
      remainingSoldToAllocate -= consumedQty;
    }

    if (product.totalStock !== totalStockAcc) {
      product.totalStock = totalStockAcc;
      await product.save();
    }

    return { totalStock: totalStockAcc, totalSold: totalSoldQty, batches };
  },

  async updateBatch(batchId, data) {
    if (!mongoose.Types.ObjectId.isValid(batchId)) {
      throw new AppError(`Invalid Batch ID format: '${batchId}'`, HTTP_STATUS.BAD_REQUEST);
    }
    const batch = await ProductBatch.findById(batchId).exec();
    if (!batch) {
      throw new AppError('Batch record not found', HTTP_STATUS.NOT_FOUND);
    }

    if (data.sellingPrice !== undefined) {
      batch.sellingPrice = Math.max(0, Number(data.sellingPrice) || 0);
    }
    if (data.purchaseRate !== undefined) {
      batch.purchaseRate = Math.max(0, Number(data.purchaseRate) || 0);
    }
    if (data.mrp !== undefined) {
      batch.mrp = Math.max(0, Number(data.mrp) || 0);
    }
    if (data.batchNumber && typeof data.batchNumber === 'string' && data.batchNumber.trim()) {
      batch.batchNumber = data.batchNumber.trim();
    }

    await batch.save();
    logger.info(`⭐ Updated ProductBatch '${batch.batchNumber}' (ID: ${batch._id}) -> Selling Price: ₹${batch.sellingPrice}`);

    await this.reconcileProductBatches(batch.productId);

    return await this.getProductById(batch.productId);
  },

  async createProduct(data) {
    if (!data || typeof data !== 'object') {
      throw new AppError('Invalid request payload', HTTP_STATUS.BAD_REQUEST);
    }

    if (!data.name || typeof data.name !== 'string' || !data.name.trim()) {
      throw new AppError('Product name is required', HTTP_STATUS.BAD_REQUEST);
    }

    const productName = data.name.trim();
    const rawBatchInput = (data.batchCode || data.batchNumber || '').toString().trim();
    const incomingBatchCode = (rawBatchInput.toUpperCase().startsWith('BATCH-') || rawBatchInput.toUpperCase().startsWith('AUTO'))
      ? ''
      : rawBatchInput;

    const brandId = data.brandId || data.companyId;
    if (!brandId) {
      throw new AppError('Brand is required', HTTP_STATUS.BAD_REQUEST);
    }
    if (!mongoose.Types.ObjectId.isValid(brandId)) {
      throw new AppError(`Invalid Brand ID format: '${brandId}'`, HTTP_STATUS.BAD_REQUEST);
    }

    if (!data.categoryId) {
      throw new AppError('Category is required', HTTP_STATUS.BAD_REQUEST);
    }
    if (!mongoose.Types.ObjectId.isValid(data.categoryId)) {
      throw new AppError(`Invalid Category ID format: '${data.categoryId}'`, HTTP_STATUS.BAD_REQUEST);
    }

    const defaultUnitId = data.defaultUnitId || data.unitId;
    if (!defaultUnitId) {
      throw new AppError('Default Unit is required', HTTP_STATUS.BAD_REQUEST);
    }
    if (!mongoose.Types.ObjectId.isValid(defaultUnitId)) {
      throw new AppError(`Invalid Unit ID format: '${defaultUnitId}'`, HTTP_STATUS.BAD_REQUEST);
    }

    // Helper regex escape function for safe mongo regex querying
    const escapeRegex = (str) => (str || '').toString().replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

    // 1. MONGODB QUERY: Find all active products matching Product Name (case-insensitive)
    const matchingProducts = await productRepository.findAll({
      name: new RegExp(`^${escapeRegex(productName)}$`, 'i'),
      isActive: true,
    });

    let isDuplicate = false;

    if (matchingProducts && matchingProducts.length > 0) {
      const matchingProductIds = matchingProducts.map((p) => p._id);

      if (incomingBatchCode) {
        // Incoming batch code exists: check if any matching product already has THIS batch code
        const existingBatch = await ProductBatch.findOne({
          productId: { $in: matchingProductIds },
          batchNumber: new RegExp(`^${escapeRegex(incomingBatchCode)}$`, 'i'),
          isActive: true,
        }).lean();

        if (existingBatch) {
          isDuplicate = true;
        }
      } else {
        // Incoming batch code is empty: check if any matching product has NO batch code (or empty batch code)
        for (const p of matchingProducts) {
          const pBatches = await ProductBatch.find({
            productId: p._id,
            isActive: true,
            batchNumber: { $not: /^BATCH-/i },
          }).lean();
          const hasNonEmptyBatch = pBatches.some((b) => b.batchNumber && b.batchNumber.toString().trim().length > 0);
          if (!hasNonEmptyBatch || pBatches.length === 0) {
            isDuplicate = true;
            break;
          }
        }
      }
    }

    const debugText =
      `\n====================================================\n` +
      `🔍 PRODUCT & BATCH DUPLICATE CHECK\n` +
      `----------------------------------------------------\n` +
      `• Incoming Product Name : '${productName}'\n` +
      `• Incoming Batch Code   : '${incomingBatchCode || 'None (Empty)'}'\n` +
      `• Matching Products     : ${matchingProducts ? matchingProducts.length : 0} found\n` +
      `• Is Duplicate          : ${isDuplicate}\n` +
      `====================================================\n`;

    logger.info(debugText);
    console.log(debugText);

    if (isDuplicate) {
      throw new AppError(
        'This Product with the same Batch Number already exists.',
        HTTP_STATUS.CONFLICT
      );
    }

    // CREATE NEW PRODUCT MASTER DOCUMENT
    const payload = {
      name: productName,
      code: (data.code && typeof data.code === 'string') ? data.code.trim() : undefined,
      barcode: (data.barcode && typeof data.barcode === 'string') ? data.barcode.trim() : undefined,
      image: (data.image && typeof data.image === 'string' && data.image.trim()) ? data.image.trim() : '/assets/urea_bag.png',
      brandId,
      categoryId: data.categoryId,
      defaultUnitId,
      hsnCode: (data.hsnCode && typeof data.hsnCode === 'string') ? data.hsnCode.trim() : undefined,
      gstRate: Number(data.gstRate) || 18,
      minimumStockAlert: Number(data.minimumStockAlert || data.minStockAlert) || 10,
      defaultPurchaseRate: Number(data.defaultPurchaseRate) || 0,
      defaultMrp: Number(data.defaultMrp) || 0,
      defaultSellingPrice: Number(data.defaultSellingPrice) || 0,
    };

    const newProduct = await productRepository.create(payload);

    if (incomingBatchCode) {
      const batchData = {
        productId: newProduct._id,
        batchNumber: incomingBatchCode,
        purchaseRate: Number(data.defaultPurchaseRate) || 0,
        mrp: Number(data.defaultMrp) || 0,
        sellingPrice: Number(data.defaultSellingPrice) || 0,
        expiryDate: data.expiryDate ? new Date(data.expiryDate) : undefined,
        quantity: 0,
      };
      await productRepository.upsertBatch(batchData);
    }

    const populatedNew = await productRepository.findByIdPopulated(newProduct._id);
    const batchesNew = await productRepository.findBatchesByProduct(newProduct._id);
    const validBatchesNew = batchesNew.filter((b) => b.batchNumber && !b.batchNumber.toUpperCase().startsWith('BATCH-'));
    const resObj = populatedNew.toObject ? populatedNew.toObject() : { ...populatedNew };

    resObj.batches = validBatchesNew;
    resObj.batchNumber = incomingBatchCode || validBatchesNew[0]?.batchNumber || undefined;
    resObj.batchCode = resObj.batchNumber;
    return resObj;
  },

  async updateProduct(id, data) {
    if (!mongoose.Types.ObjectId.isValid(id)) {
      throw new AppError(`Invalid Product ID format: '${id}'`, HTTP_STATUS.BAD_REQUEST);
    }
    const product = await productRepository.findById(id);
    if (!product) {
      throw new AppError('Product not found', HTTP_STATUS.NOT_FOUND);
    }

    const payload = {};
    if (data.name) payload.name = data.name.trim();
    if (data.code !== undefined) payload.code = data.code?.trim() || undefined;
    if (data.barcode !== undefined) payload.barcode = data.barcode?.trim() || undefined;
    if (data.image !== undefined) payload.image = (data.image && typeof data.image === 'string' && data.image.trim()) ? data.image.trim() : '/assets/urea_bag.png';

    const brandId = data.brandId || data.companyId;
    if (brandId) {
      if (!mongoose.Types.ObjectId.isValid(brandId)) {
        throw new AppError(`Invalid Brand ID format: '${brandId}'`, HTTP_STATUS.BAD_REQUEST);
      }
      payload.brandId = brandId;
    }

    if (data.categoryId) {
      if (!mongoose.Types.ObjectId.isValid(data.categoryId)) {
        throw new AppError(`Invalid Category ID format: '${data.categoryId}'`, HTTP_STATUS.BAD_REQUEST);
      }
      payload.categoryId = data.categoryId;
    }

    const defaultUnitId = data.defaultUnitId || data.unitId;
    if (defaultUnitId) {
      if (!mongoose.Types.ObjectId.isValid(defaultUnitId)) {
        throw new AppError(`Invalid Unit ID format: '${defaultUnitId}'`, HTTP_STATUS.BAD_REQUEST);
      }
      payload.defaultUnitId = defaultUnitId;
    }

    if (data.hsnCode !== undefined) payload.hsnCode = data.hsnCode?.trim() || undefined;
    if (data.gstRate !== undefined) payload.gstRate = Number(data.gstRate) || 0;
    if (data.minimumStockAlert !== undefined || data.minStockAlert !== undefined) {
      payload.minimumStockAlert = Number(data.minimumStockAlert || data.minStockAlert) || 10;
    }
    if (data.defaultPurchaseRate !== undefined) payload.defaultPurchaseRate = Number(data.defaultPurchaseRate) || 0;
    if (data.defaultMrp !== undefined) payload.defaultMrp = Number(data.defaultMrp) || 0;
    if (data.defaultSellingPrice !== undefined) payload.defaultSellingPrice = Number(data.defaultSellingPrice) || 0;

    await productRepository.update(id, payload);

    const rawBatchInput = (data.batchCode || data.batchNumber || '').toString().trim();
    const batchCode = (rawBatchInput.toUpperCase().startsWith('BATCH-') || rawBatchInput.toUpperCase().startsWith('AUTO'))
      ? ''
      : rawBatchInput;

    if (batchCode) {
      await productRepository.upsertBatch({
        productId: id,
        batchNumber: batchCode,
        purchaseRate: Number(data.defaultPurchaseRate) || product.defaultPurchaseRate || 0,
        mrp: Number(data.defaultMrp) || product.defaultMrp || 0,
        sellingPrice: Number(data.defaultSellingPrice) || product.defaultSellingPrice || 0,
        expiryDate: data.expiryDate ? new Date(data.expiryDate) : undefined,
        quantity: 0,
      });
    }

    const updatedPopulated = await productRepository.findByIdPopulated(id);
    const batches = await productRepository.findBatchesByProduct(id);
    const validBatches = batches.filter((b) => b.batchNumber && !b.batchNumber.toUpperCase().startsWith('BATCH-'));
    const resObj = updatedPopulated.toObject ? updatedPopulated.toObject() : { ...updatedPopulated };

    resObj.batches = validBatches;
    resObj.batchNumber = batchCode || validBatches[0]?.batchNumber || undefined;
    resObj.batchCode = resObj.batchNumber;
    return resObj;
  },

  async deactivateProduct(id, userId = null) {
    if (!id || !mongoose.Types.ObjectId.isValid(id)) {
      throw new AppError(`Invalid Product ID format: '${id}'`, HTTP_STATUS.BAD_REQUEST);
    }
    const product = await Product.findById(id).exec();
    if (!product) {
      throw new AppError('Product not found', HTTP_STATUS.NOT_FOUND);
    }

    product.isActive = false;
    product.deletedAt = new Date();
    if (userId && mongoose.Types.ObjectId.isValid(userId)) {
      product.deletedBy = userId;
    }

    await product.save();
    logger.info(`🔒 Soft Deleted Product '${product.name}' [${id}] -> isActive: false, deletedAt: ${product.deletedAt}`);
    return product;
  },

  async restoreProduct(id) {
    if (!id || !mongoose.Types.ObjectId.isValid(id)) {
      throw new AppError(`Invalid Product ID format: '${id}'`, HTTP_STATUS.BAD_REQUEST);
    }
    const product = await Product.findById(id).exec();
    if (!product) {
      throw new AppError('Product not found', HTTP_STATUS.NOT_FOUND);
    }

    product.isActive = true;
    product.deletedAt = null;
    product.deletedBy = null;
    await product.save();
    logger.info(`🔓 Restored Product '${product.name}' [${id}] -> isActive: true`);
    return product;
  },

  async getProductHistory(id) {
    if (!mongoose.Types.ObjectId.isValid(id)) {
      throw new AppError(`Invalid Product ID format: '${id}'`, HTTP_STATUS.BAD_REQUEST);
    }
    const productDoc = await productRepository.findByIdPopulated(id);
    if (!productDoc) {
      throw new AppError('Product not found', HTTP_STATUS.NOT_FOUND);
    }

    const productId = new mongoose.Types.ObjectId(id);

    // 1. Fetch Purchase Items for this product from DB
    const rawPurchaseItems = await PurchaseItem.find({ productId })
      .populate({
        path: 'purchaseId',
        select: 'purchaseNumber supplierInvoiceNumber purchaseDate supplierId',
        populate: { path: 'supplierId', select: 'name' },
      })
      .sort({ createdAt: -1 })
      .lean()
      .exec();

    const purchaseHistory = rawPurchaseItems.map((item) => {
      const pQty = Number(item.quantity || 0);
      const pRate = Number(item.purchaseRate || 0);
      const sPrice = Number(item.sellingPrice || 0);
      const pDate = item.purchaseId?.purchaseDate || item.createdAt;
      return {
        id: item._id.toString(),
        date: pDate ? new Date(pDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : 'N/A',
        rawDate: pDate,
        invoiceNumber: item.purchaseId?.supplierInvoiceNumber || item.purchaseId?.purchaseNumber || 'PUR-REF',
        batchNumber: item.batchNumber || 'N/A',
        quantity: pQty,
        purchaseRate: pRate,
        sellingPrice: sPrice,
        amount: Number(item.totalAmount || pQty * pRate),
        supplierId: item.purchaseId?.supplierId?._id ? item.purchaseId.supplierId._id.toString() : null,
        supplierName: item.purchaseId?.supplierId?.name || 'General Supplier',
      };
    });

    const totalPurchasedQty = purchaseHistory.reduce((sum, p) => sum + p.quantity, 0);
    const lastPurchaseDate = purchaseHistory.length > 0 ? purchaseHistory[0].date : null;

    // 2. Fetch Sales Invoices containing this product from DB
    const rawSalesInvoices = await SalesInvoice.find({ 'items.productId': productId })
      .sort({ date: -1, createdAt: -1 })
      .lean()
      .exec();

    const now = new Date();
    const currentMonth = now.getMonth();
    const currentYear = now.getFullYear();

    let totalSoldQty = 0;
    let monthlySalesQty = 0;
    let yearlySalesQty = 0;
    let monthlyRevenue = 0;
    let yearlyRevenue = 0;
    const salesHistory = [];

    rawSalesInvoices.forEach((inv) => {
      const invDate = inv.date ? new Date(inv.date) : new Date(inv.createdAt);
      const isThisMonth = invDate.getMonth() === currentMonth && invDate.getFullYear() === currentYear;
      const isThisYear = invDate.getFullYear() === currentYear;

      (inv.items || []).forEach((item) => {
        if (item.productId && item.productId.toString() === id) {
          const qty = Number(item.quantity || 0);
          const sPrice = Number(item.unitPrice || 0);
          const cogs = Number(item.purchaseCostRate || 0);
          const totalAmt = Number(item.totalAmount || qty * sPrice);
          const lineProfit = Number(item.lineProfit !== undefined ? item.lineProfit : ((sPrice - cogs) * qty));

          totalSoldQty += qty;
          if (isThisMonth) {
            monthlySalesQty += qty;
            monthlyRevenue += totalAmt;
          }
          if (isThisYear) {
            yearlySalesQty += qty;
            yearlyRevenue += totalAmt;
          }

          if (Array.isArray(item.batchAllocations) && item.batchAllocations.length > 0) {
            item.batchAllocations.forEach((alloc, aIdx) => {
              const aQty = Number(alloc.quantity || 0);
              const aSelling = Number(alloc.sellingPrice || sPrice);
              const aCogs = Number(alloc.purchaseRate || cogs);
              const aProfit = (aSelling - aCogs) * aQty;
              salesHistory.push({
                id: `${inv._id}_${item._id}_${aIdx}`,
                date: invDate.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
                rawDate: invDate,
                invoiceNumber: inv.invoiceNumber,
                customerName: inv.customerName || 'Retail Customer',
                batchNumber: alloc.batchNumber || item.batchNumber || 'N/A',
                quantity: aQty,
                sellingPrice: aSelling,
                cogs: aCogs,
                profit: aProfit,
                unitProfit: aQty > 0 ? aProfit / aQty : 0,
                totalAmount: aQty * aSelling,
              });
            });
          } else {
            salesHistory.push({
              id: `${inv._id}_${item._id}`,
              date: invDate.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
              rawDate: invDate,
              invoiceNumber: inv.invoiceNumber,
              customerName: inv.customerName || 'Retail Customer',
              batchNumber: item.batchNumber || 'N/A',
              quantity: qty,
              sellingPrice: sPrice,
              cogs: cogs,
              profit: lineProfit,
              unitProfit: qty > 0 ? lineProfit / qty : 0,
              totalAmount: totalAmt,
            });
          }
        }
      });
    });

    const lastSaleDate = salesHistory.length > 0 ? salesHistory[0].date : null;

    // 3. Fetch StockLedger entries or synthesize complete Stock History audit log
    const ledgerEntries = await StockLedger.find({ productId })
      .sort({ timestamp: -1, createdAt: -1 })
      .lean()
      .exec();

    let stockHistory = [];

    if (ledgerEntries.length > 0) {
      stockHistory = ledgerEntries.map((l) => ({
        id: l._id.toString(),
        date: l.timestamp
          ? new Date(l.timestamp).toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })
          : new Date(l.createdAt).toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }),
        rawDate: l.timestamp || l.createdAt,
        type: l.transactionType || 'PURCHASE',
        batchNumber: l.batchNumber || 'N/A',
        quantity: l.quantity,
        formattedQuantity: l.quantity > 0 ? `+${l.quantity}` : `${l.quantity}`,
        purchaseRate: Number(l.purchaseRate || 0),
        sellingPrice: Number(l.sellingPrice || 0),
        stockAfter: Number(l.currentStock || 0),
        previousStock: Number(l.previousStock || 0),
        reference: l.referenceNumber || (l.referenceId ? l.referenceId.toString() : 'SYS-REF'),
      }));
    } else {
      const mergedEvents = [];

      purchaseHistory.forEach((p) => {
        mergedEvents.push({
          type: 'PURCHASE',
          date: p.rawDate,
          batchNumber: p.batchNumber,
          quantity: p.quantity,
          purchaseRate: p.purchaseRate,
          sellingPrice: p.sellingPrice,
          reference: p.invoiceNumber,
        });
      });

      salesHistory.forEach((s) => {
        mergedEvents.push({
          type: 'SALE',
          date: s.rawDate,
          batchNumber: s.batchNumber,
          quantity: -s.quantity,
          purchaseRate: s.cogs,
          sellingPrice: s.sellingPrice,
          reference: s.invoiceNumber,
        });
      });

      mergedEvents.sort((a, b) => new Date(a.date) - new Date(b.date));

      let runningStock = 0;
      const historyWithStock = mergedEvents.map((evt, idx) => {
        const prev = runningStock;
        runningStock += evt.quantity;
        return {
          id: `synth_${idx}`,
          date: evt.date
            ? new Date(evt.date).toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })
            : 'N/A',
          rawDate: evt.date,
          type: evt.type,
          batchNumber: evt.batchNumber || 'N/A',
          quantity: evt.quantity,
          formattedQuantity: evt.quantity > 0 ? `+${evt.quantity}` : `${evt.quantity}`,
          purchaseRate: evt.purchaseRate,
          sellingPrice: evt.sellingPrice,
          previousStock: prev,
          stockAfter: runningStock,
          reference: evt.reference,
        };
      });

      stockHistory = historyWithStock.reverse();
    }

    return {
      productId: id,
      totalPurchasedQty,
      totalSoldQty,
      lastPurchaseDate,
      lastSaleDate,
      monthlySalesQty,
      yearlySalesQty,
      monthlyRevenue,
      yearlyRevenue,
      purchaseHistory,
      salesHistory,
      stockHistory,
    };
  },

  async getProductInventoryDetails(productId) {
    if (!productId || !mongoose.Types.ObjectId.isValid(productId)) {
      throw new AppError('Invalid Product ID', HTTP_STATUS.BAD_REQUEST);
    }

    const id = productId.toString();
    const product = await productRepository.findById(productId);
    if (!product) {
      throw new AppError('Product not found', HTTP_STATUS.NOT_FOUND);
    }

    // 1. Fetch Purchase Items for this product from DB (handling both ObjectId & String IDs)
    const rawPurchaseItems = await PurchaseItem.find({
      $or: [{ productId: productId }, { productId: id }],
    })
      .populate({
        path: 'purchaseId',
        select: 'purchaseNumber supplierInvoiceNumber purchaseDate supplierId',
        populate: { path: 'supplierId', select: 'name' },
      })
      .sort({ createdAt: -1 })
      .lean()
      .exec();

    const purchaseHistory = rawPurchaseItems.map((item) => {
      const pQty = Number(item.quantity || 0);
      const pRate = Number(item.purchaseRate || 0);
      return {
        id: item._id.toString(),
        date: item.purchaseId?.purchaseDate
          ? new Date(item.purchaseId.purchaseDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
          : new Date(item.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
        rawDate: item.purchaseId?.purchaseDate || item.createdAt,
        invoiceNumber: item.purchaseId?.supplierInvoiceNumber || item.purchaseId?.purchaseNumber || 'PUR-REF',
        supplierId: item.purchaseId?.supplierId?._id ? item.purchaseId.supplierId._id.toString() : null,
        supplierName: item.purchaseId?.supplierId?.name || 'General Supplier',
        quantity: pQty,
        rate: pRate,
        amount: Number(item.totalAmount || pQty * pRate),
        batchNumber: item.batchNumber || null,
      };
    });

    const totalInward = purchaseHistory.reduce((sum, p) => sum + p.quantity, 0);
    const lastPurchase = purchaseHistory.length > 0 ? purchaseHistory[0] : null;

    const latestPurchasePrice = lastPurchase && lastPurchase.rate > 0
      ? lastPurchase.rate
      : Number(product.defaultPurchaseRate || product.purchasePrice || 0);

    // 2. Fetch Sales Invoices containing this product from DB
    const rawSalesInvoices = await SalesInvoice.find({
      $or: [
        { 'items.productId': productId },
        { 'items.productId': id },
        { 'items.id': id },
        { 'items._id': productId },
      ],
    })
      .sort({ date: -1, createdAt: -1 })
      .lean()
      .exec();

    const now = new Date();
    const currentMonth = now.getMonth();
    const currentYear = now.getFullYear();

    let totalOutward = 0;
    let monthlySalesQty = 0;
    let yearlySalesQty = 0;
    let monthlyRevenue = 0;
    let yearlyRevenue = 0;
    const salesHistory = [];

    rawSalesInvoices.forEach((inv) => {
      const invDate = inv.date ? new Date(inv.date) : new Date(inv.createdAt);
      const isThisMonth = invDate.getMonth() === currentMonth && invDate.getFullYear() === currentYear;
      const isThisYear = invDate.getFullYear() === currentYear;

      (inv.items || []).forEach((item) => {
        const itemProdId = item.productId || item.id || item._id;
        if (itemProdId && itemProdId.toString() === id) {
          const qty = Number(item.quantity || item.qty || 0);
          const price = Number(item.unitPrice || item.price || 0);
          const totalAmt = Number(item.totalAmount || qty * price);

          totalOutward += qty;
          if (isThisMonth) {
            monthlySalesQty += qty;
            monthlyRevenue += totalAmt;
          }
          if (isThisYear) {
            yearlySalesQty += qty;
            yearlyRevenue += totalAmt;
          }

          salesHistory.push({
            id: `${inv._id}_${item._id || itemProdId}`,
            date: invDate.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
            rawDate: invDate,
            invoiceNumber: inv.invoiceNumber,
            customerName: inv.customerName || 'Retail Customer',
            quantity: qty,
            price: price,
            amount: totalAmt,
          });
        }
      });
    });

    const lastSale = salesHistory.length > 0 ? salesHistory[0] : null;
    const currentStock = Math.max(0, Number(product.totalStock ?? product.currentStock ?? (totalInward - totalOutward)));
    const stockValue = currentStock * latestPurchasePrice;

    return {
      product: {
        _id: product._id,
        name: product.name,
        code: product.code,
        image: product.image,
        brandName: product.brandId?.name || 'N/A',
        categoryName: product.categoryId?.name || 'Uncategorized',
        unitName: product.defaultUnitId?.shortName || product.unit || 'Bag',
        minimumStockAlert: product.minimumStockAlert || 10,
        defaultSellingPrice: product.defaultSellingPrice || 0,
        defaultPurchaseRate: product.defaultPurchaseRate || 0,
      },
      currentStock,
      stockValue,
      latestPurchasePrice,
      totalInward,
      totalOutward,
      lastPurchase,
      lastSale,
      monthlySales: {
        quantity: monthlySalesQty,
        revenue: monthlyRevenue,
      },
      yearlySales: {
        quantity: yearlySalesQty,
        revenue: yearlyRevenue,
      },
      purchaseHistory,
      salesHistory,
      purchaseHistoryCount: purchaseHistory.length,
      salesHistoryCount: salesHistory.length,
    };
  },
};
